services:
  backend:
    image: ghcr.io/xcirno1/nutricare-backend:latest
    container_name: nutricare-backend
    env_file: .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/xcirno1/nutricare-frontend:latest
    container_name: nutricare-frontend
    env_file: .env
    ports:
      - "3001:3000"
    restart: unless-stopped
