services:
  backend:
    image: ghcr.io/xcirno1/nutricare-backend:latest
    container_name: nutricare-backend
    env_file: .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/xcirno1/nutricare-frontend:latest
    container_name: nutricare-frontend
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  nutricare-nginx:
    image: nginx:alpine
    container_name: nutricare-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - nutricare-frontend
      - nutricare-backend
    restart: unless-stopped
